variable "cluster_name" {
  description = "The name of the Kind cluster"
  type        = string
  default     = "booking-app-cluster"
}

variable "kind_config_file" {
  description = "Path to the Kind cluster configuration file"
  type        = string
  default     = "kind-cluster-config.yaml"
}

variable "kubeconfig_path" {
  description = "Path to the kubeconfig file generated by Kind"
  type        = string
  default     = "~/.kube/config"
}