apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: backend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3100
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:password@database.database.svc.cluster.local:5432/booking"
