apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80 # Portul expus în cluster
      targetPort: 3000 # Portul pe care îl ascultă containerul
  type: ClusterIP # Accesibil doar din cluster
